<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\QuestionBank;

class QuestionBankBossHardSeeder extends Seeder
{
    public function run(): void
    {
        $commonAttributes = [
            'bank_group'       => 6,
            'bank_name'        => 'OOP & Database - Boss',
            'bank_icon'        => '🏆',
            'bank_description' => 'Bank soal PHP lanjutan (Boss Level): advanced OOP, deep database integration, dan complex regex.',
        ];

        $questions = [
            [
                'level'         => 'Hard',
                'soal_text'     => 'Jika class B mewarisi class A dan memanggil "parent::hello() . \' dan B\'", apa string outputnya jika method hello() di class A mereturn "Halo dari A"?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Halo dari A',
                'pilihan_b'     => 'Halo dari B',
                'pilihan_c'     => 'Halo dari A dan B',
                'pilihan_d'     => 'Error',
                'jawaban_benar' => 'Halo dari A dan B',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Property dengan access modifier private di class induk...',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Bisa diakses langsung dari class turunan',
                'pilihan_b'     => 'Tidak bisa diakses dari class turunan secara langsung',
                'pilihan_c'     => 'Otomatis menjadi public di class turunan',
                'pilihan_d'     => 'Bisa diakses dari luar class',
                'jawaban_benar' => 'Tidak bisa diakses dari class turunan secara langsung',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Berapa hasil dari fungsi matematika absolute abs(-99) di PHP?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '-99',
                'pilihan_b'     => '99',
                'pilihan_c'     => '0',
                'pilihan_d'     => 'Error',
                'jawaban_benar' => '99',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Meskipun variabel dideklarasikan sebagai string $x = "10", apa hasil dari operasi aritmatika $x + 5 di PHP?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '105',
                'pilihan_b'     => '10 5',
                'pilihan_c'     => '15',
                'pilihan_d'     => 'Error',
                'jawaban_benar' => '15',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Manakah sintaks yang benar untuk melakukan koneksi PDO ke database MySQL lokal?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'new PDO("mysql", "localhost", "root", "")',
                'pilihan_b'     => 'new PDO("mysql:host=localhost;dbname=db", "root", "")',
                'pilihan_c'     => 'PDO::connect("localhost", "root", "", "db")',
                'pilihan_d'     => 'new mysqli("localhost", "root", "", "db")',
                'jawaban_benar' => 'new PDO("mysql:host=localhost;dbname=db", "root", "")',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Karakter apa saja yang sah digunakan sebagai parameter placeholder dalam prepared statement PDO?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '%s',
                'pilihan_b'     => '{$var} atau :nama',
                'pilihan_c'     => '? atau :nama',
                'pilihan_d'     => '@nilai',
                'jawaban_benar' => '? atau :nama',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Superglobal $_SERVER["REQUEST_METHOD"] mengembalikan nilai berupa...',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Nama file PHP yang sedang dijalankan',
                'pilihan_b'     => 'HTTP method yang digunakan (GET, POST, dll)',
                'pilihan_c'     => 'IP address server',
                'pilihan_d'     => 'Versi PHP yang digunakan',
                'jawaban_benar' => 'HTTP method yang digunakan (GET, POST, dll)',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Berapa angka hasil dari fungsi perpangkatan pow(2, 10) di PHP?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '20',
                'pilihan_b'     => '210',
                'pilihan_c'     => '512',
                'pilihan_d'     => '1024',
                'jawaban_benar' => '1024',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Manakah pola regex (Regular Expression) yang benar untuk mencocokkan HANYA karakter angka (0-9)?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '/[a-z]/',
                'pilihan_b'     => '/[0-9]+/',
                'pilihan_c'     => '/[A-Z]/',
                'pilihan_d'     => '/\w+/',
                'jawaban_benar' => '/[0-9]+/',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method getter dalam OOP PHP biasanya digunakan untuk...',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Menghapus nilai property',
                'pilihan_b'     => 'Mengubah nilai property dari luar class',
                'pilihan_c'     => 'Membaca nilai property private atau protected dari luar class',
                'pilihan_d'     => 'Membuat object baru dari class',
                'jawaban_benar' => 'Membaca nilai property private atau protected dari luar class',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method fetch_assoc() pada MySQLi mengembalikan baris hasil query dalam bentuk...',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Object',
                'pilihan_b'     => 'Array indexed',
                'pilihan_c'     => 'Array associative',
                'pilihan_d'     => 'String JSON',
                'jawaban_benar' => 'Array associative',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Berapa string hasil dari formatting fungsi number_format(1234567.5, 2, ".", ",") di PHP?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '1234567.50',
                'pilihan_b'     => '1,234,567.50',
                'pilihan_c'     => '1.234.567,50',
                'pilihan_d'     => '1234567,50',
                'jawaban_benar' => '1,234,567.50',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Untuk menangkap nilai "5" dari parameter URL ?id=5&nama=budi, superglobal mana yang harus dipanggil?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '$_POST["id"]',
                'pilihan_b'     => '$_SESSION["id"]',
                'pilihan_c'     => '$_GET["id"]',
                'pilihan_d'     => '$_SERVER["id"]',
                'jawaban_benar' => '$_GET["id"]',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Jika class Persegi mewarisi property protected $sisi dari class Shapes yang diinisialisasi angka 5, berapa nilai yang direturn method luas() yang berisi return $this->sisi * $this->sisi?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '5',
                'pilihan_b'     => '10',
                'pilihan_c'     => '20',
                'pilihan_d'     => '25',
                'jawaban_benar' => '25',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Fungsi preg_match_all() memiliki perbedaan spesifik dari preg_match() yaitu...',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'preg_match_all() hanya mencari kecocokan pertama',
                'pilihan_b'     => 'preg_match_all() menemukan SEMUA kecocokan dalam string',
                'pilihan_c'     => 'preg_match_all() mengganti pola dengan string baru',
                'pilihan_d'     => 'preg_match_all() hanya bekerja pada array',
                'jawaban_benar' => 'preg_match_all() menemukan SEMUA kecocokan dalam string',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Berapa nilai integer bulat yang dihasilkan dari proses casting intval("3.99")?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '3.99',
                'pilihan_b'     => '4',
                'pilihan_c'     => '3',
                'pilihan_d'     => 'Error',
                'jawaban_benar' => '3',
                'bobot_xp'      => 30,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Mengatur atribut PDO::ATTR_ERRMODE menjadi PDO::ERRMODE_EXCEPTION memiliki tujuan untuk...',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Membuat koneksi otomatis ke database',
                'pilihan_b'     => 'Membuat PDO melempar exception saat terjadi error query',
                'pilihan_c'     => 'Mematikan semua error reporting',
                'pilihan_d'     => 'Mengaktifkan mode debug visual',
                'jawaban_benar' => 'Membuat PDO melempar exception saat terjadi error query',
                'bobot_xp'      => 30,
            ],
        ];

        foreach ($questions as $question) {
            QuestionBank::create(array_merge($commonAttributes, $question));
        }
    }
}