<?php

namespace Database\Seeders;

use App\Models\QuestionBank;
use Illuminate\Database\Seeder;

class QuestionBankSeeder extends Seeder
{
    public function run(): void
    {
        $questions = [
            // EASY LEVEL (25 Questions) - PHP Basics, Syntax, Variables
            [
                'level' => 'Easy',
                'soal_text' => 'Apa kepanjangan dari PHP?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Personal Home Page',
                'pilihan_b' => 'Private Home Page',
                'pilihan_c' => 'PHP: Hypertext Preprocessor',
                'pilihan_d' => 'Program Hypertext Processor',
                'jawaban_benar' => 'PHP: Hypertext Preprocessor',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Simbol apa yang digunakan untuk memulai variabel di PHP?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '&',
                'pilihan_b' => '$',
                'pilihan_c' => '#',
                'pilihan_d' => '%',
                'jawaban_benar' => '$',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Perintah apa yang digunakan untuk menampilkan teks ke layar di PHP?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'print_r',
                'pilihan_b' => 'echo',
                'pilihan_c' => 'display',
                'pilihan_d' => 'show',
                'jawaban_benar' => 'echo',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Setiap statement di PHP harus diakhiri dengan simbol...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '.',
                'pilihan_b' => ':',
                'pilihan_c' => ';',
                'pilihan_d' => ',',
                'jawaban_benar' => ';',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Manakah penulisan komentar satu baris yang benar di PHP?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '<!-- Komentar -->',
                'pilihan_b' => '// Komentar',
                'pilihan_c' => '/* Komentar */',
                'pilihan_d' => '** Komentar',
                'jawaban_benar' => '// Komentar',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Tipe data apa yang digunakan untuk menyimpan teks di PHP?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Integer',
                'pilihan_b' => 'Boolean',
                'pilihan_c' => 'String',
                'pilihan_d' => 'Float',
                'jawaban_benar' => 'String',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Operator aritmatika untuk penjumlahan adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '*',
                'pilihan_b' => '/',
                'pilihan_c' => '+',
                'pilihan_d' => '-',
                'jawaban_benar' => '+',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Operator aritmatika untuk sisa bagi (modulus) adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '/',
                'pilihan_b' => '%',
                'pilihan_c' => '#',
                'pilihan_d' => '@',
                'jawaban_benar' => '%',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Fungsi untuk menghitung panjang string adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'len()',
                'pilihan_b' => 'length()',
                'pilihan_c' => 'strlen()',
                'pilihan_d' => 'count()',
                'jawaban_benar' => 'strlen()',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Fungsi untuk menghitung jumlah elemen dalam array adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'sizeof()',
                'pilihan_b' => 'count()',
                'pilihan_c' => 'length()',
                'pilihan_d' => 'total()',
                'jawaban_benar' => 'count()',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Manakah yang merupakan tipe data boolean?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '"True"',
                'pilihan_b' => '1',
                'pilihan_c' => 'true',
                'pilihan_d' => '0',
                'jawaban_benar' => 'true',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Operator perbandingan "sama dengan" adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '=',
                'pilihan_b' => '==',
                'pilihan_c' => '===',
                'pilihan_d' => '!=',
                'jawaban_benar' => '==',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Operator perbandingan "identik" (nilai dan tipe data sama) adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '=',
                'pilihan_b' => '==',
                'pilihan_c' => '===',
                'pilihan_d' => '!==',
                'jawaban_benar' => '===',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Operator logika "DAN" adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '||',
                'pilihan_b' => '&&',
                'pilihan_c' => '!',
                'pilihan_d' => 'AND',
                'jawaban_benar' => '&&',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Operator logika "ATAU" adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '||',
                'pilihan_b' => '&&',
                'pilihan_c' => '!',
                'pilihan_d' => 'OR',
                'jawaban_benar' => '||',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Struktur kontrol untuk percabangan adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'for',
                'pilihan_b' => 'while',
                'pilihan_c' => 'if',
                'pilihan_d' => 'foreach',
                'jawaban_benar' => 'if',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Struktur kontrol untuk perulangan dengan jumlah iterasi yang diketahui adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'while',
                'pilihan_b' => 'do-while',
                'pilihan_c' => 'for',
                'pilihan_d' => 'switch',
                'jawaban_benar' => 'for',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Cara mendefinisikan konstanta di PHP adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '$const',
                'pilihan_b' => 'define()',
                'pilihan_c' => 'constant()',
                'pilihan_d' => 'var',
                'jawaban_benar' => 'define()',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Tag pembuka PHP adalah...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => '<?php',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Tag penutup PHP adalah...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => '?>',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Apa output dari echo 5 + 5?',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => '10',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Apa output dari echo "Hello" . "World"?',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => 'HelloWorld',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Variabel di PHP bersifat case-sensitive. (Benar/Salah)',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Benar',
                'pilihan_b' => 'Salah',
                'pilihan_c' => 'Tergantung OS',
                'pilihan_d' => 'Hanya di function',
                'jawaban_benar' => 'Benar',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Index array dimulai dari angka...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => '0',
                'bobot_xp' => 10,
            ],
            [
                'level' => 'Easy',
                'soal_text' => 'Fungsi untuk mengonversi string menjadi huruf kecil semua adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'toupper()',
                'pilihan_b' => 'tolower()',
                'pilihan_c' => 'strtolower()',
                'pilihan_d' => 'strtoupper()',
                'jawaban_benar' => 'strtolower()',
                'bobot_xp' => 10,
            ],

            // MEDIUM LEVEL (25 Questions) - Functions, Arrays, Loops
            [
                'level' => 'Medium',
                'soal_text' => 'Bagaimana cara membuat fungsi di PHP?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'create function myFunc()',
                'pilihan_b' => 'function myFunc()',
                'pilihan_c' => 'def myFunc()',
                'pilihan_d' => 'func myFunc()',
                'jawaban_benar' => 'function myFunc()',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Apa itu Associative Array?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Array dengan index angka',
                'pilihan_b' => 'Array dengan index string (key)',
                'pilihan_c' => 'Array multidimensi',
                'pilihan_d' => 'Array kosong',
                'jawaban_benar' => 'Array dengan index string (key)',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Perulangan yang paling tepat untuk mengakses setiap elemen array adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'for',
                'pilihan_b' => 'while',
                'pilihan_c' => 'foreach',
                'pilihan_d' => 'do-while',
                'jawaban_benar' => 'foreach',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi untuk menggabungkan elemen array menjadi string adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'explode()',
                'pilihan_b' => 'implode()',
                'pilihan_c' => 'join()',
                'pilihan_d' => 'merge()',
                'jawaban_benar' => 'implode()',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi untuk memecah string menjadi array berdasarkan delimiter adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'explode()',
                'pilihan_b' => 'implode()',
                'pilihan_c' => 'split()',
                'pilihan_d' => 'break()',
                'jawaban_benar' => 'explode()',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Keyword "global" digunakan untuk...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Membuat variabel lokal',
                'pilihan_b' => 'Mengakses variabel global di dalam fungsi',
                'pilihan_c' => 'Menghapus variabel',
                'pilihan_d' => 'Mendeklarasikan konstanta',
                'jawaban_benar' => 'Mengakses variabel global di dalam fungsi',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Apa output dari: $x = 5; function tes() { echo $x; } tes(); ?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '5',
                'pilihan_b' => 'Error / Undefined variable',
                'pilihan_c' => '0',
                'pilihan_d' => 'Null',
                'jawaban_benar' => 'Error / Undefined variable',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi array_push() digunakan untuk...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Menghapus elemen terakhir',
                'pilihan_b' => 'Menambah elemen di akhir array',
                'pilihan_c' => 'Menambah elemen di awal array',
                'pilihan_d' => 'Menghapus elemen pertama',
                'jawaban_benar' => 'Menambah elemen di akhir array',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi array_pop() digunakan untuk...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Menghapus elemen terakhir',
                'pilihan_b' => 'Menambah elemen di akhir array',
                'pilihan_c' => 'Menambah elemen di awal array',
                'pilihan_d' => 'Menghapus elemen pertama',
                'jawaban_benar' => 'Menghapus elemen terakhir',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Apa itu scope variabel?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Tipe data variabel',
                'pilihan_b' => 'Nilai variabel',
                'pilihan_c' => 'Cakupan di mana variabel dapat diakses',
                'pilihan_d' => 'Nama variabel',
                'jawaban_benar' => 'Cakupan di mana variabel dapat diakses',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Manakah cara penulisan array multidimensi yang benar?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => '$arr = [[1,2], [3,4]];',
                'pilihan_b' => '$arr = {1,2,3,4};',
                'pilihan_c' => '$arr = (1,2,3,4);',
                'pilihan_d' => '$arr = [1:2, 3:4];',
                'jawaban_benar' => '$arr = [[1,2], [3,4]];',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi in_array() berguna untuk...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Mengurutkan array',
                'pilihan_b' => 'Mengecek apakah nilai ada di dalam array',
                'pilihan_c' => 'Menghitung jumlah array',
                'pilihan_d' => 'Menggabungkan array',
                'jawaban_benar' => 'Mengecek apakah nilai ada di dalam array',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi sort() mengurutkan array secara...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Descending (besar ke kecil)',
                'pilihan_b' => 'Ascending (kecil ke besar)',
                'pilihan_c' => 'Acak',
                'pilihan_d' => 'Berdasarkan key',
                'jawaban_benar' => 'Ascending (kecil ke besar)',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi rsort() mengurutkan array secara...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Descending (besar ke kecil)',
                'pilihan_b' => 'Ascending (kecil ke besar)',
                'pilihan_c' => 'Acak',
                'pilihan_d' => 'Berdasarkan key',
                'jawaban_benar' => 'Descending (besar ke kecil)',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Apa kegunaan statement "return" dalam fungsi?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Menghentikan eksekusi script',
                'pilihan_b' => 'Mengembalikan nilai dari fungsi',
                'pilihan_c' => 'Mencetak nilai ke layar',
                'pilihan_d' => 'Mengulang fungsi',
                'jawaban_benar' => 'Mengembalikan nilai dari fungsi',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Parameter default pada fungsi ditulis dengan cara...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'function tes($a = 1)',
                'pilihan_b' => 'function tes($a : 1)',
                'pilihan_c' => 'function tes($a == 1)',
                'pilihan_d' => 'function tes(default $a = 1)',
                'jawaban_benar' => 'function tes($a = 1)',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi date("Y-m-d") akan menghasilkan format...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Tanggal-Bulan-Tahun (01-12-2023)',
                'pilihan_b' => 'Tahun-Bulan-Tanggal (2023-12-01)',
                'pilihan_c' => 'Jam-Menit-Detik',
                'pilihan_d' => 'Hari-Bulan-Tahun',
                'jawaban_benar' => 'Tahun-Bulan-Tanggal (2023-12-01)',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi include() dan require() bedanya adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Tidak ada bedanya',
                'pilihan_b' => 'require() akan fatal error jika file tidak ada, include() hanya warning',
                'pilihan_c' => 'include() akan fatal error jika file tidak ada, require() hanya warning',
                'pilihan_d' => 'include() hanya untuk file html',
                'jawaban_benar' => 'require() akan fatal error jika file tidak ada, include() hanya warning',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Superglobal variable untuk mendapatkan data dari form method POST adalah...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => '$_POST',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Superglobal variable untuk mendapatkan data dari URL (query string) adalah...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => '$_GET',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi untuk menghapus spasi di awal dan akhir string adalah...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => 'trim()',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi untuk mengganti teks dalam string adalah...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => 'str_replace()',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Operator increment adalah...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => '++',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Operator decrement adalah...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => '--',
                'bobot_xp' => 20,
            ],
            [
                'level' => 'Medium',
                'soal_text' => 'Fungsi untuk mengecek apakah variabel sudah diset atau belum adalah...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => 'isset()',
                'bobot_xp' => 20,
            ],

            // HARD LEVEL (24 Questions) - OOP, Advanced Logic, Security
            [
                'level' => 'Hard',
                'soal_text' => 'Apa itu OOP?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Object Oriented Programming',
                'pilihan_b' => 'Object Oriented Process',
                'pilihan_c' => 'Only One Programming',
                'pilihan_d' => 'Open Oriented Programming',
                'jawaban_benar' => 'Object Oriented Programming',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Keyword untuk membuat class adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'object',
                'pilihan_b' => 'class',
                'pilihan_c' => 'new',
                'pilihan_d' => 'define',
                'jawaban_benar' => 'class',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Keyword untuk membuat instance (objek) dari class adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'create',
                'pilihan_b' => 'make',
                'pilihan_c' => 'new',
                'pilihan_d' => 'instance',
                'jawaban_benar' => 'new',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Variabel di dalam class disebut...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Method',
                'pilihan_b' => 'Property',
                'pilihan_c' => 'Function',
                'pilihan_d' => 'Constant',
                'jawaban_benar' => 'Property',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Function di dalam class disebut...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Method',
                'pilihan_b' => 'Property',
                'pilihan_c' => 'Variable',
                'pilihan_d' => 'Attribute',
                'jawaban_benar' => 'Method',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Keyword $this merujuk pada...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Class itu sendiri',
                'pilihan_b' => 'Objek saat ini (current object)',
                'pilihan_c' => 'Variabel global',
                'pilihan_d' => 'Parent class',
                'jawaban_benar' => 'Objek saat ini (current object)',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Method __construct() dijalankan ketika...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Objek dihapus',
                'pilihan_b' => 'Objek dibuat',
                'pilihan_c' => 'Method dipanggil',
                'pilihan_d' => 'Terjadi error',
                'jawaban_benar' => 'Objek dibuat',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Visibilitas "public" artinya...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Hanya bisa diakses di class itu sendiri',
                'pilihan_b' => 'Bisa diakses dari mana saja',
                'pilihan_c' => 'Hanya bisa diakses di class turunan',
                'pilihan_d' => 'Tidak bisa diakses',
                'jawaban_benar' => 'Bisa diakses dari mana saja',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Visibilitas "private" artinya...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Hanya bisa diakses di class itu sendiri',
                'pilihan_b' => 'Bisa diakses dari mana saja',
                'pilihan_c' => 'Hanya bisa diakses di class turunan',
                'pilihan_d' => 'Bisa diakses dari luar class',
                'jawaban_benar' => 'Hanya bisa diakses di class itu sendiri',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Visibilitas "protected" artinya...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Hanya bisa diakses di class itu sendiri',
                'pilihan_b' => 'Bisa diakses dari mana saja',
                'pilihan_c' => 'Bisa diakses di class itu sendiri dan turunannya',
                'pilihan_d' => 'Sama dengan public',
                'jawaban_benar' => 'Bisa diakses di class itu sendiri dan turunannya',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Konsep pewarisan class disebut...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Polymorphism',
                'pilihan_b' => 'Encapsulation',
                'pilihan_c' => 'Inheritance',
                'pilihan_d' => 'Abstraction',
                'jawaban_benar' => 'Inheritance',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Keyword untuk mewarisi class adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'implements',
                'pilihan_b' => 'extends',
                'pilihan_c' => 'inherits',
                'pilihan_d' => 'uses',
                'jawaban_benar' => 'extends',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'SQL Injection dapat dicegah dengan menggunakan...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Prepared Statements (PDO)',
                'pilihan_b' => 'Menggunakan $_GET',
                'pilihan_c' => 'Mematikan error reporting',
                'pilihan_d' => 'Menggunakan md5',
                'jawaban_benar' => 'Prepared Statements (PDO)',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Fungsi password_hash() digunakan untuk...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Mengenkripsi password dengan aman',
                'pilihan_b' => 'Mendekripsi password',
                'pilihan_c' => 'Menampilkan password',
                'pilihan_d' => 'Mengubah password jadi text',
                'jawaban_benar' => 'Mengenkripsi password dengan aman',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Fungsi password_verify() digunakan untuk...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Membuat password baru',
                'pilihan_b' => 'Memverifikasi hash password',
                'pilihan_c' => 'Menghapus password',
                'pilihan_d' => 'Mengirim password ke email',
                'jawaban_benar' => 'Memverifikasi hash password',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Apa itu CSRF?',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Cross-Site Request Forgery',
                'pilihan_b' => 'Cascading Style Request Form',
                'pilihan_c' => 'Code Source Request File',
                'pilihan_d' => 'Cross-Site Resource File',
                'jawaban_benar' => 'Cross-Site Request Forgery',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Di Laravel, proteksi CSRF dilakukan dengan token...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => '@csrf',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Namespace digunakan untuk...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Mengorganisir class dan menghindari konflik nama',
                'pilihan_b' => 'Memberi nama variabel',
                'pilihan_c' => 'Membuat database',
                'pilihan_d' => 'Menghubungkan file CSS',
                'jawaban_benar' => 'Mengorganisir class dan menghindari konflik nama',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Composer adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Text Editor',
                'pilihan_b' => 'Dependency Manager untuk PHP',
                'pilihan_c' => 'Web Server',
                'pilihan_d' => 'Database Manager',
                'jawaban_benar' => 'Dependency Manager untuk PHP',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'File konfigurasi utama untuk dependency Composer adalah...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => 'composer.json',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Perintah untuk menginstall dependency dari composer.json adalah...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => 'composer install',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Design pattern MVC singkatan dari...',
                'tipe' => 'short_answer',
                'pilihan_a' => null,
                'pilihan_b' => null,
                'pilihan_c' => null,
                'pilihan_d' => null,
                'jawaban_benar' => 'Model View Controller',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Bagian MVC yang menangani logika bisnis dan data adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Model',
                'pilihan_b' => 'View',
                'pilihan_c' => 'Controller',
                'pilihan_d' => 'Router',
                'jawaban_benar' => 'Model',
                'bobot_xp' => 30,
            ],
            [
                'level' => 'Hard',
                'soal_text' => 'Bagian MVC yang menangani tampilan user interface adalah...',
                'tipe' => 'multiple_choice',
                'pilihan_a' => 'Model',
                'pilihan_b' => 'View',
                'pilihan_c' => 'Controller',
                'pilihan_d' => 'Database',
                'jawaban_benar' => 'View',
                'bobot_xp' => 30,
            ],
        ];

        foreach ($questions as $question) {
            QuestionBank::create($question);
        }
    }
}
