<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\QuestionBank;

class QuestionBankSeeder3 extends Seeder
{
    /**
     * Run the database seeds.
     * Bank 3: JavaScript (ES6, DOM, Async)
     */
    public function run(): void
    {
        // 1. Data Statis (Sama untuk semua soal di file ini)
        $commonAttributes = [
            'bank_group'       => 3,
            'bank_name'        => 'JavaScript',
            'bank_icon'        => 'javascript',
            'bank_description' => 'ES6+, DOM manipulation, and async programming',
        ];

        // 2. Data Unik per Soal
        $questions = [
            // ==================== EASY LEVEL ====================
            [
                'level'         => 'Easy',
                'soal_text'     => 'Keyword untuk mendeklarasikan variabel yang tidak bisa diubah nilainya?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'let',
                'pilihan_b'     => 'var',
                'pilihan_c'     => 'const',
                'pilihan_d'     => 'static',
                'jawaban_benar' => 'const',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Function untuk menampilkan output ke console?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'console.log',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Operator untuk strict equality check di JavaScript?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '==',
                'pilihan_b'     => '===',
                'pilihan_c'     => '=',
                'pilihan_d'     => '!=',
                'jawaban_benar' => '===',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Method untuk mengambil element HTML berdasarkan ID?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'getElementById',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Tipe data untuk nilai true/false di JavaScript?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'boolean',
                'pilihan_b'     => 'bool',
                'pilihan_c'     => 'bit',
                'pilihan_d'     => 'binary',
                'jawaban_benar' => 'boolean',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Method array untuk menambah element di akhir?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'push',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Kata kunci untuk mendefinisikan function di JavaScript?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'function',
                'pilihan_b'     => 'func',
                'pilihan_c'     => 'def',
                'pilihan_d'     => 'method',
                'jawaban_benar' => 'function',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Method untuk menghilangkan whitespace di awal dan akhir string?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'trim',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Operator untuk type checking di JavaScript?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'typeof',
                'pilihan_b'     => 'type',
                'pilihan_c'     => 'instanceof',
                'pilihan_d'     => 'is',
                'jawaban_benar' => 'typeof',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Event listener untuk klik di JavaScript?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'click',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Method untuk mengubah array menjadi string?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'join()',
                'pilihan_b'     => 'toString()',
                'pilihan_c'     => 'concat()',
                'pilihan_d'     => 'stringify()',
                'jawaban_benar' => 'join()',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Keyword untuk menghentikan loop?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'break',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Cara membuat comment satu baris di JavaScript?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '//',
                'pilihan_b'     => '#',
                'pilihan_c'     => '/* */',
                'pilihan_d'     => '--',
                'jawaban_benar' => '//',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Method untuk mengecek apakah string mengandung substring?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'includes',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Nilai yang merepresentasikan "tidak ada nilai" di JavaScript?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'null',
                'pilihan_b'     => 'none',
                'pilihan_c'     => 'empty',
                'pilihan_d'     => 'void',
                'jawaban_benar' => 'null',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Property untuk mengambil panjang array?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'length',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Keyword untuk melempar error di JavaScript?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'throw',
                'pilihan_b'     => 'error',
                'pilihan_c'     => 'raise',
                'pilihan_d'     => 'except',
                'jawaban_benar' => 'throw',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Method untuk mengubah string menjadi lowercase?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'toLowerCase',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Operator logika untuk AND di JavaScript?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '&&',
                'pilihan_b'     => '||',
                'pilihan_c'     => 'and',
                'pilihan_d'     => '&',
                'jawaban_benar' => '&&',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Method untuk menghapus element terakhir array?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'pop',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Fungsi JavaScript dijalankan dimana?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Browser atau Node.js',
                'pilihan_b'     => 'Hanya browser',
                'pilihan_c'     => 'Hanya server',
                'pilihan_d'     => 'Database',
                'jawaban_benar' => 'Browser atau Node.js',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Keyword untuk mendeklarasikan variabel dengan block scope?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'let',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Method untuk membulatkan angka ke bawah?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Math.floor()',
                'pilihan_b'     => 'Math.ceil()',
                'pilihan_c'     => 'Math.round()',
                'pilihan_d'     => 'Math.down()',
                'jawaban_benar' => 'Math.floor()',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Tag HTML untuk menyisipkan JavaScript eksternal?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'script',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Karakter untuk mengakses property object?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '.',
                'pilihan_b'     => '->',
                'pilihan_c'     => '::',
                'pilihan_d'     => '-',
                'jawaban_benar' => '.',
                'bobot_xp'      => 10,
            ],

            // ==================== MEDIUM LEVEL ====================
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method modern untuk query selector CSS di JavaScript?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'querySelector',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Event yang terjadi saat DOM selesai dimuat (tanpa tunggu CSS/image)?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'DOMContentLoaded',
                'pilihan_b'     => 'load',
                'pilihan_c'     => 'ready',
                'pilihan_d'     => 'complete',
                'jawaban_benar' => 'DOMContentLoaded',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk mencegah default behavior event?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'preventDefault',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Array method untuk iterasi setiap element?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'forEach()',
                'pilihan_b'     => 'loop()',
                'pilihan_c'     => 'iterate()',
                'pilihan_d'     => 'each()',
                'jawaban_benar' => 'forEach()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Cara membuat object literal di JavaScript?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => '{}',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk filter array berdasarkan kondisi?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'filter()',
                'pilihan_b'     => 'find()',
                'pilihan_c'     => 'where()',
                'pilihan_d'     => 'select()',
                'jawaban_benar' => 'filter()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Property untuk mengakses parent element di DOM?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'parentElement',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk transform array ke bentuk baru?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'map()',
                'pilihan_b'     => 'convert()',
                'pilihan_c'     => 'change()',
                'pilihan_d'     => 'transform()',
                'jawaban_benar' => 'map()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Cara menambahkan class ke element?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'classList.add',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Spread operator di JavaScript menggunakan simbol?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '...',
                'pilihan_b'     => '***',
                'pilihan_c'     => '---',
                'pilihan_d'     => '+++',
                'jawaban_benar' => '...',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk menggabungkan dua array?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'concat',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Destructuring assignment digunakan untuk?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Unpack array/object values',
                'pilihan_b'     => 'Delete variables',
                'pilihan_c'     => 'Merge objects',
                'pilihan_d'     => 'Create classes',
                'jawaban_benar' => 'Unpack array/object values',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk membuat element HTML baru?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'createElement',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Template literals menggunakan karakter?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Backtick ``',
                'pilihan_b'     => 'Single quote \'\'',
                'pilihan_c'     => 'Double quote ""',
                'pilihan_d'     => 'Bracket []',
                'jawaban_benar' => 'Backtick ``',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk menghapus event listener?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'removeEventListener',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Arrow function syntax menggunakan operator?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '=>',
                'pilihan_b'     => '->',
                'pilihan_c'     => '::',
                'pilihan_d'     => '~>',
                'jawaban_benar' => '=>',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk mencari index element di array?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'indexOf',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Cara mengambil data attribute dari element?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'dataset',
                'pilihan_b'     => 'getAttribute',
                'pilihan_c'     => 'data',
                'pilihan_d'     => 'attribute',
                'jawaban_benar' => 'dataset',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk reduce array menjadi single value?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'reduce',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Property untuk mengambil nilai input form?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'value',
                'pilihan_b'     => 'data',
                'pilihan_c'     => 'text',
                'pilihan_d'     => 'content',
                'jawaban_benar' => 'value',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk parsing JSON string?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'JSON.parse',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Cara menjalankan function setelah delay tertentu?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'setTimeout',
                'pilihan_b'     => 'delay',
                'pilihan_c'     => 'wait',
                'pilihan_d'     => 'pause',
                'jawaban_benar' => 'setTimeout',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk convert object ke JSON string?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'JSON.stringify',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Event bubbling vs capturing, mana yang terjadi duluan?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Capturing',
                'pilihan_b'     => 'Bubbling',
                'pilihan_c'     => 'Bersamaan',
                'pilihan_d'     => 'Random',
                'jawaban_benar' => 'Capturing',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Cara membuat array dengan nilai default tertentu?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'Array.fill',
                'bobot_xp'      => 15,
            ],

            // ==================== HARD LEVEL ====================
            [
                'level'         => 'Hard',
                'soal_text'     => 'Promise state setelah berhasil resolve?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'fulfilled',
                'pilihan_b'     => 'resolved',
                'pilihan_c'     => 'completed',
                'pilihan_d'     => 'done',
                'jawaban_benar' => 'fulfilled',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Keyword untuk menunggu promise resolve?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'await',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method untuk handle error di promise chain?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'catch()',
                'pilihan_b'     => 'error()',
                'pilihan_c'     => 'fail()',
                'pilihan_d'     => 'exception()',
                'jawaban_benar' => 'catch()',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Function yang bisa pause dan resume dengan yield?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'generator',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Closure di JavaScript adalah?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Function dengan akses ke outer scope',
                'pilihan_b'     => 'Function yang menutup program',
                'pilihan_c'     => 'Loop yang tertutup',
                'pilihan_d'     => 'Block scope',
                'jawaban_benar' => 'Function dengan akses ke outer scope',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method Promise untuk run multiple promises parallel?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'Promise.all',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Apa itu event loop di JavaScript?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Mechanism untuk handle asynchronous operations',
                'pilihan_b'     => 'Infinite loop',
                'pilihan_c'     => 'Event listener',
                'pilihan_d'     => 'For loop variant',
                'jawaban_benar' => 'Mechanism untuk handle asynchronous operations',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Cara membuat class di ES6?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'class',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Module system di ES6 menggunakan keyword?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'import/export',
                'pilihan_b'     => 'require/module',
                'pilihan_c'     => 'include/exclude',
                'pilihan_d'     => 'use/provide',
                'jawaban_benar' => 'import/export',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Proxy object digunakan untuk?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'intercept object operations',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'WeakMap berbeda dari Map karena?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Keys are weakly referenced (garbage collected)',
                'pilihan_b'     => 'Lebih lambat',
                'pilihan_c'     => 'Tidak bisa store data',
                'pilihan_d'     => 'Hanya untuk number',
                'jawaban_benar' => 'Keys are weakly referenced (garbage collected)',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method async function harus return?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'Promise',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Symbol di ES6 digunakan untuk?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Create unique identifier',
                'pilihan_b'     => 'Mathematical operation',
                'pilihan_c'     => 'String formatting',
                'pilihan_d'     => 'Number conversion',
                'jawaban_benar' => 'Create unique identifier',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Cara membuat immutable object?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'Object.freeze',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Rest parameter di function syntax?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '...args',
                'pilihan_b'     => '*args',
                'pilihan_c'     => '&args',
                'pilihan_d'     => '@args',
                'jawaban_benar' => '...args',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method untuk iterate object keys?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'Object.keys',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Fetch API return type?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Promise',
                'pilihan_b'     => 'Observable',
                'pilihan_c'     => 'Callback',
                'pilihan_d'     => 'Stream',
                'jawaban_benar' => 'Promise',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Memoization pattern digunakan untuk?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'cache function results',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Debouncing vs Throttling, mana yang delay execution?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Debouncing',
                'pilihan_b'     => 'Throttling',
                'pilihan_c'     => 'Keduanya',
                'pilihan_d'     => 'Tidak ada',
                'jawaban_benar' => 'Debouncing',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Service Worker digunakan untuk?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'offline caching',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Web Workers berjalan di?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Background thread',
                'pilihan_b'     => 'Main thread',
                'pilihan_c'     => 'Server side',
                'pilihan_d'     => 'Database',
                'jawaban_benar' => 'Background thread',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Currying di JavaScript adalah?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'transform function with multiple args to nested functions',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Optional chaining operator?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '?.',
                'pilihan_b'     => '??',
                'pilihan_c'     => '?:',
                'pilihan_d'     => '!.',
                'jawaban_benar' => '?.',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Nullish coalescing operator?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => '??',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Cara create private field di class ES2022?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '#property',
                'pilihan_b'     => '_property',
                'pilihan_c'     => 'private property',
                'pilihan_d'     => '$property',
                'jawaban_benar' => '#property',
                'bobot_xp'      => 20,
            ],
        ];

        // 3. Loop dan Gabungkan (Merge)
        foreach ($questions as $question) {
            QuestionBank::create(array_merge($commonAttributes, $question));
        }
    }
}