<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\QuestionBank;

class QuestionBankSeeder2 extends Seeder
{
    /**
     * Run the database seeds.
     * Bank 2: PHP Advanced (OOP, Laravel, Database)
     * Total: 75 questions (25 Easy, 25 Medium, 25 Hard)
     */
    public function run(): void
    {
        // 1. Data Statis (Sama untuk semua soal di file ini)
        $commonAttributes = [
            'bank_group'       => 2,
            'bank_name'        => 'PHP Advanced',
            'bank_icon'        => 'code_blocks',
            'bank_description' => 'OOP, Laravel framework, and advanced PHP topics',
        ];

        // 2. Data Unik per Soal
        $questions = [
            // ==================== EASY LEVEL (25 Questions) - OOP Basics ====================
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa keyword yang digunakan untuk mendefinisikan class di PHP?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'class',
                'pilihan_b'     => 'object',
                'pilihan_c'     => 'define',
                'pilihan_d'     => 'create',
                'jawaban_benar' => 'class',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Method apa yang otomatis dipanggil saat object dibuat?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => '__construct',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Visibility modifier apa yang membuat property hanya bisa diakses dalam class itu sendiri?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'public',
                'pilihan_b'     => 'private',
                'pilihan_c'     => 'protected',
                'pilihan_d'     => 'internal',
                'jawaban_benar' => 'private',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Keyword apa yang digunakan untuk mewariskan class?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'inherit',
                'pilihan_b'     => 'extends',
                'pilihan_c'     => 'implements',
                'pilihan_d'     => 'uses',
                'jawaban_benar' => 'extends',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa keyword untuk mengakses property atau method dari parent class?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'parent',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Method apa yang dipanggil saat object dihancurkan?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '__destruct',
                'pilihan_b'     => '__destroy',
                'pilihan_c'     => '__delete',
                'pilihan_d'     => '__remove',
                'jawaban_benar' => '__destruct',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa keyword untuk membuat property atau method static?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'static',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Keyword apa yang digunakan untuk mengimplementasikan interface?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'extends',
                'pilihan_b'     => 'implements',
                'pilihan_c'     => 'uses',
                'pilihan_d'     => 'include',
                'jawaban_benar' => 'implements',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa operator yang digunakan untuk mengakses property object?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '.',
                'pilihan_b'     => '->',
                'pilihan_c'     => '::',
                'pilihan_d'     => '=>',
                'jawaban_benar' => '->',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa keyword untuk mengakses constant class?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => '::',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa keyword untuk merujuk instance class sendiri?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '$this',
                'pilihan_b'     => '$self',
                'pilihan_c'     => '$me',
                'pilihan_d'     => '$object',
                'jawaban_benar' => '$this',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Keyword apa untuk mencegah class diwariskan?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'final',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa keyword untuk mendefinisikan abstract class?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'abstract',
                'pilihan_b'     => 'interface',
                'pilihan_c'     => 'virtual',
                'pilihan_d'     => 'base',
                'jawaban_benar' => 'abstract',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Berapa jumlah class yang bisa di-extend oleh satu class di PHP?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '0',
                'pilihan_b'     => '1',
                'pilihan_c'     => '2',
                'pilihan_d'     => 'Unlimited',
                'jawaban_benar' => '1',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Method __toString() digunakan untuk apa?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'mengkonversi object ke string',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa fungsi dari namespace di PHP?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Mengelompokkan class',
                'pilihan_b'     => 'Membuat variable',
                'pilihan_c'     => 'Mengatur permission',
                'pilihan_d'     => 'Menyimpan data',
                'jawaban_benar' => 'Mengelompokkan class',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Keyword apa untuk menggunakan namespace?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'use',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa nama metode autoloading class di PHP modern?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'spl_autoload_register',
                'pilihan_b'     => 'autoload',
                'pilihan_c'     => 'load_class',
                'pilihan_d'     => 'require_class',
                'jawaban_benar' => 'spl_autoload_register',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Trait di PHP digunakan untuk apa?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Reuse code tanpa inheritance',
                'pilihan_b'     => 'Membuat interface',
                'pilihan_c'     => 'Mendefinisikan constant',
                'pilihan_d'     => 'Menyimpan data',
                'jawaban_benar' => 'Reuse code tanpa inheritance',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Magic method __get() digunakan untuk?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'mengakses property yang tidak accessible',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa perbedaan public dan protected?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Protected hanya bisa diakses class sendiri dan turunannya',
                'pilihan_b'     => 'Tidak ada perbedaan',
                'pilihan_c'     => 'Public lebih aman',
                'pilihan_d'     => 'Protected lebih cepat',
                'jawaban_benar' => 'Protected hanya bisa diakses class sendiri dan turunannya',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Keyword untuk mengimport trait ke dalam class?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'use',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Operator instanceof digunakan untuk?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Mengecek apakah object instance dari class tertentu',
                'pilihan_b'     => 'Membuat instance baru',
                'pilihan_c'     => 'Menghapus instance',
                'pilihan_d'     => 'Clone instance',
                'jawaban_benar' => 'Mengecek apakah object instance dari class tertentu',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa fungsi clone keyword?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'menyalin object',
                'bobot_xp'      => 10,
            ],
            [
                'level'         => 'Easy',
                'soal_text'     => 'Apa ekstensi file class di PSR-4?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '.php',
                'pilihan_b'     => '.class',
                'pilihan_c'     => '.inc',
                'pilihan_d'     => '.phtml',
                'jawaban_benar' => '.php',
                'bobot_xp'      => 10,
            ],

            // ==================== MEDIUM LEVEL (25 Questions) - Laravel Basics ====================
            [
                'level'         => 'Medium',
                'soal_text'     => 'Artisan command untuk membuat controller baru di Laravel?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'php artisan make:controller',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method apa di route untuk menangani POST request?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Route::post()',
                'pilihan_b'     => 'Route::send()',
                'pilihan_c'     => 'Route::submit()',
                'pilihan_d'     => 'Route::request()',
                'jawaban_benar' => 'Route::post()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Directive Blade untuk menampilkan data tanpa escape?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => '{!! !!}',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method Eloquent untuk mengambil semua data?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'all()',
                'pilihan_b'     => 'get()',
                'pilihan_c'     => 'fetch()',
                'pilihan_d'     => 'select()',
                'jawaban_benar' => 'all()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'File konfigurasi database Laravel ada di folder?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'config',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Command untuk menjalankan migration?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'php artisan migrate',
                'pilihan_b'     => 'php artisan db:migrate',
                'pilihan_c'     => 'php artisan run:migration',
                'pilihan_d'     => 'php artisan migration:run',
                'jawaban_benar' => 'php artisan migrate',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk validasi request di Laravel?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'validate',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Helper function untuk redirect di Laravel?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'redirect()',
                'pilihan_b'     => 'goto()',
                'pilihan_c'     => 'forward()',
                'pilihan_d'     => 'move()',
                'jawaban_benar' => 'redirect()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Middleware default untuk autentikasi di Laravel?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'auth',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk membuat relasi one-to-many di Eloquent?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'hasMany()',
                'pilihan_b'     => 'hasOne()',
                'pilihan_c'     => 'belongsTo()',
                'pilihan_d'     => 'manyToOne()',
                'jawaban_benar' => 'hasMany()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Blade directive untuk loop?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => '@foreach',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk soft delete di Eloquent?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'delete()',
                'pilihan_b'     => 'softDelete()',
                'pilihan_c'     => 'remove()',
                'pilihan_d'     => 'trash()',
                'jawaban_benar' => 'delete()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Helper untuk mengambil nilai dari .env?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'env',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Property Eloquent untuk mendefinisikan tabel?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '$table',
                'pilihan_b'     => '$tableName',
                'pilihan_c'     => '$database',
                'pilihan_d'     => '$model',
                'jawaban_benar' => '$table',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Command artisan untuk membuat model dan migration sekaligus?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'php artisan make:model -m',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Facade untuk mengirim email di Laravel?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Mail',
                'pilihan_b'     => 'Email',
                'pilihan_c'     => 'Send',
                'pilihan_d'     => 'Message',
                'jawaban_benar' => 'Mail',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Property untuk mass assignment di model?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => '$fillable',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk pagination di Laravel?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'paginate()',
                'pilihan_b'     => 'page()',
                'pilihan_c'     => 'limit()',
                'pilihan_d'     => 'slice()',
                'jawaban_benar' => 'paginate()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Blade directive untuk include partial view?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => '@include',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Helper untuk membuat URL di Laravel?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'url()',
                'pilihan_b'     => 'link()',
                'pilihan_c'     => 'path()',
                'pilihan_d'     => 'route()',
                'jawaban_benar' => 'url()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Command untuk clear cache di Laravel?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'php artisan cache:clear',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method untuk join tables di Query Builder?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'join()',
                'pilihan_b'     => 'merge()',
                'pilihan_c'     => 'combine()',
                'pilihan_d'     => 'link()',
                'jawaban_benar' => 'join()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Session helper di Laravel untuk menyimpan data?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'session',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Method eloquent untuk update atau create record?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'updateOrCreate()',
                'pilihan_b'     => 'saveOrUpdate()',
                'pilihan_c'     => 'upsert()',
                'pilihan_d'     => 'merge()',
                'jawaban_benar' => 'updateOrCreate()',
                'bobot_xp'      => 15,
            ],
            [
                'level'         => 'Medium',
                'soal_text'     => 'Folder default untuk controller di Laravel?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'app/Http/Controllers',
                'bobot_xp'      => 15,
            ],

            // ==================== HARD LEVEL (25 Questions) - Advanced Laravel ====================
            [
                'level'         => 'Hard',
                'soal_text'     => 'Apa perbedaan Service Provider dan Service Container di Laravel?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Provider mendaftarkan service, Container menyimpan binding',
                'pilihan_b'     => 'Tidak ada perbedaan',
                'pilihan_c'     => 'Provider lebih cepat',
                'pilihan_d'     => 'Container hanya untuk database',
                'jawaban_benar' => 'Provider mendaftarkan service, Container menyimpan binding',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method untuk binding interface ke implementation di Service Provider?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'bind',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Command untuk membuat custom artisan command?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'php artisan make:command',
                'pilihan_b'     => 'php artisan create:command',
                'pilihan_c'     => 'php artisan new:command',
                'pilihan_d'     => 'php artisan command:make',
                'jawaban_benar' => 'php artisan make:command',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Event listener di Laravel diregister dimana?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'EventServiceProvider',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method untuk defer Service Provider loading?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => '$defer = true',
                'pilihan_b'     => 'defer()',
                'pilihan_c'     => 'lazy()',
                'pilihan_d'     => 'delayed()',
                'jawaban_benar' => '$defer = true',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Interface untuk Job yang bisa di-queue?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'ShouldQueue',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Macroable trait di Laravel digunakan untuk?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Extend class dengan method baru di runtime',
                'pilihan_b'     => 'Membuat macro excel',
                'pilihan_c'     => 'Optimize performance',
                'pilihan_d'     => 'Database pooling',
                'jawaban_benar' => 'Extend class dengan method baru di runtime',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method untuk database transaction di Laravel?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'DB::transaction',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'N+1 problem di Eloquent bisa diselesaikan dengan?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Eager Loading (with)',
                'pilihan_b'     => 'Lazy Loading',
                'pilihan_c'     => 'Cache',
                'pilihan_d'     => 'Index database',
                'jawaban_benar' => 'Eager Loading (with)',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Observer Pattern di Laravel digunakan untuk?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'listen to model events',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Middleware terminate method dipanggil kapan?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Setelah response dikirim ke browser',
                'pilihan_b'     => 'Sebelum controller',
                'pilihan_c'     => 'Saat error',
                'pilihan_d'     => 'Saat aplikasi shutdown',
                'jawaban_benar' => 'Setelah response dikirim ke browser',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method untuk custom validation rule di Laravel?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'make:rule',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Policy di Laravel digunakan untuk?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Authorization logic',
                'pilihan_b'     => 'Route protection',
                'pilihan_c'     => 'Database access',
                'pilihan_d'     => 'CSRF protection',
                'jawaban_benar' => 'Authorization logic',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Package manager PHP yang digunakan Laravel?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'Composer',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method untuk broadcast event ke WebSocket?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'broadcast()',
                'pilihan_b'     => 'emit()',
                'pilihan_c'     => 'send()',
                'pilihan_d'     => 'push()',
                'jawaban_benar' => 'broadcast()',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Rate limiting di Laravel menggunakan facade?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'RateLimiter',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Accessor dan Mutator di Eloquent digunakan untuk?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Modify attribute saat get/set',
                'pilihan_b'     => 'Database indexing',
                'pilihan_c'     => 'Query optimization',
                'pilihan_d'     => 'Cache management',
                'jawaban_benar' => 'Modify attribute saat get/set',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method untuk schedule task di Laravel?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'schedule',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Horizon digunakan untuk monitoring?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'Queue jobs',
                'pilihan_b'     => 'Database queries',
                'pilihan_c'     => 'HTTP requests',
                'pilihan_d'     => 'File uploads',
                'jawaban_benar' => 'Queue jobs',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'File untuk mendefinisikan API routes?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'routes/api.php',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Sanctum di Laravel digunakan untuk?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'API authentication',
                'pilihan_b'     => 'Database migration',
                'pilihan_c'     => 'File storage',
                'pilihan_d'     => 'Email verification',
                'jawaban_benar' => 'API authentication',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method untuk membuat scope global di Eloquent?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'addGlobalScope',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Collection method untuk transform data?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'map()',
                'pilihan_b'     => 'change()',
                'pilihan_c'     => 'modify()',
                'pilihan_d'     => 'alter()',
                'jawaban_benar' => 'map()',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Testing framework default di Laravel?',
                'tipe'          => 'short_answer',
                'jawaban_benar' => 'PHPUnit',
                'bobot_xp'      => 20,
            ],
            [
                'level'         => 'Hard',
                'soal_text'     => 'Method untuk mock object di Laravel testing?',
                'tipe'          => 'multiple_choice',
                'pilihan_a'     => 'mock()',
                'pilihan_b'     => 'fake()',
                'pilihan_c'     => 'stub()',
                'pilihan_d'     => 'dummy()',
                'jawaban_benar' => 'mock()',
                'bobot_xp'      => 20,
            ],
        ];

        // 3. Loop dan Gabungkan (Merge)
        foreach ($questions as $question) {
            QuestionBank::create(array_merge($commonAttributes, $question));
        }
    }
}